# Change these first
owner: Ballaual # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Froxlor
    url: https://froxlor.ballaual.de/
  - name: Homepage
    url: https://ballaual.de/
  - name: Easy-Wi
    url: https://ew.ballaual.de/
  - name: Ark Server
    check: "tcp-ping"
    url: 88.198.15.44
    port: 7779
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/ark.png
  - name: Minecraft Server
    check: "tcp-ping"
    url: 88.198.15.44
    port: 25565
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/minecraft.png
    
assignees:
  - Ballaual

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/Ballaual/status/master/assets/icon.svg
  name: Upptime
  theme: night
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: https://ballaual.github.io/status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
