# Change these first
owner: Ballaual # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Froxlor
    url: https://froxlor.ballaual.de/
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/froxlor.png
  - name: Pterodactyl
    url: https://gs.ballaual.de/
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/pterodactyl.png
  - name: Homepage
    url: https://ballaual.de/
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/homepage.png
  - name: Rspamd
    url: https://ballaual.de/rspamd/
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/rspamd.png
  - name: phpMyAdmin
    url: https://ballaual.de/phpmyadmin/
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/phpmyadmin.png
  - name: Roundcube
    url: https://ballaual.de/mail/
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/roundcube.png
  - name: ARK: Survival Evolved
    check: "tcp-ping"
    url: 88.198.15.44
    port: 7779
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/ark.png
  - name: Counter-Strike 2
    check: "tcp-ping"
    url: 88.198.15.44
    port: 27015
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/counter-strike.png
  - name: Icarus
    check: "tcp-ping"
    url: 88.198.15.44
    port: 17777
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/icarus.png
  - name: Minecraft Paper
    check: "tcp-ping"
    url: 88.198.15.44
    port: 25565
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/minecraft.png
  - name: Palworld
    check: "tcp-ping"
    url: 88.198.15.44
    port: 8211
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/palworld.png
  - name: Teamspeak
    check: "tcp-ping"
    url: 88.198.15.44
    port: 10011
    icon: https://raw.githubusercontent.com/Ballaual/status/master/assets/teamspeak.png
    
assignees:
  - Ballaual

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ballaual.de
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/Ballaual/status/master/assets/icon.svg
  name: Status
  theme: night
  introTitle: "**Informationen:**"
  introMessage: ---
  navbar:
    - title: Status
      href: https://status.ballaual.de
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      target: _blank
    - title: Kontakt
      href: https://discord.com/users/475642657490599937
      target: _blank

i18n:
  activeIncidents: Aktuelle Ereignisse
  allSystemsOperational: Alle Systeme sind funktionsfähig
  incidentReport: "Ereignis #$NUMBER Details →"
  activeIncidentSummary: Seit $DATE mit $POSTS Kommentaren
  incidentTitle: Ereignis $NUMBER Details
  incidentDetails: Ereignisdetails
  incidentFixed: Behoben
  incidentOngoing: Aktiv
  incidentOpenedAt: Begonnen am
  incidentClosedAt: Geschlossen am
  incidentViewOnGitHub: Auf GitHub anzeigen
  incidentCommentSummary: Veröffentlicht am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Ereginissen
  pastIncidents: Vergangene Ereignisse
  pastIncidentsResolved: Behoben nach $MINUTES Minuten mit $POSTS Kommentaren
  liveStatus: Live Status
  overallUptime: "Online: $UPTIME"
  overallUptimeTitle: Durchschnittlich Online
  averageResponseTime: "Ping: $TIMEms"
  averageResponseTimeTitle: Durchschnittlicher Ping
  sevelDayResponseTime: 7-Tage Ping
  responseTimeMs: Ping (ms)
  up: Online
  down: Offline
  degraded: Beeinträchtigt
  ms: ms
  loading: Lädt
  navGitHub: GitHub
  footer: Diese Seite wird von [Upptime](https://upptime.js.org) unterstützt
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Vergangene Wartungsarbeiten
  scheduledMaintenance: Geplante Wartungsarbeiten
  scheduledMaintenanceSummaryStarted: Begonnen am $DATE für voraussichtlich $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für voraussichtlich $DURATION Minuten
  startedAt: Begonnen am
  startsAt: Beginnt am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Beendet
  incidentScheduled: Geplant
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: Gesamt

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
